### ISSUE TITLE
Meaning of CCL

### ISSUE THREAD

**Issue by jamadagni** [fstudio/ccl#1]
Hello. I see you have exported https://code.google.com/p/ccl/ to GitHub.

Please correct the description in the page https://github.com/fstudio/ccl/. It currently says: "A Compiler system for windows". Actually CCL stands for C Container Library since that's what it is meant for. Please correct it. Thanks.

**Comment by fcharlie** [comment]
OK  Updated,

**Comment by jamadagni** [comment]
Sorry but by visiting https://github.com/fstudio/ccl I still see "Compiler system for windows" and not "C Container Library"...

**Comment by fcharlie** [comment]
OK I read ccl.pdf ,is a Container Library ,changed it
